import React, { useState } from 'react'
import { DollarSign, Landmark, Clock, Users, Repeat, LineChart, Info } from 'lucide-react'

const REPORT_TYPES = [
    { icon: DollarSign, title: "Savings Summary Report", desc: "Deposit balances, growth and account activity across all savings products." },
    { icon: Landmark, title: "Loan Portfolio Report", desc: "Disbursements, repayments, outstanding balances and status breakdown." },
    { icon: Clock, title: "Overdue Loans Report", desc: "Full list of overdue accounts, days past due and recovery status." },
    { icon: Users, title: "Customer Growth Report", desc: "New registrations, churn and active member trends over time." },
    { icon: Repeat, title: "Transaction Report", desc: "Deposits, withdrawals and transfers for any custom date range." },
    { icon: LineChart, title: "Branch Performance Summary", desc: "Combined KPI snapshot - savings, loans, income and growth in one view." },
];

const ReportsSection = () => {
    const [notice, setNotice] = useState("");

    const notConnected = (action, reportTitle) => {
        setNotice(`"${reportTitle}" can't ${action} yet - no report-generation endpoint exists on the backend.`);
    };

    return (
        <div className='flex flex-col gap-5'>

            <div>
                <h1 className='text-2xl font-serif font-semibold text-gray-800'>Reports</h1>
                <p className='text-sm text-gray-500 mt-1'>Generate and download branch performance reports</p>
            </div>

            {notice && (
                <div className='flex items-center gap-2 bg-sky-50 border border-sky-200 text-sky-700 text-sm rounded-xl px-4 py-3'>
                    <Info size={15} className='flex-shrink-0' /> {notice}
                </div>
            )}

            <div>
                <div className='flex items-center justify-between mb-3'>
                    <h2 className='font-serif font-semibold text-lg text-gray-800'>Generate a Report</h2>
                    <p className='text-xs text-gray-400'>Choose a report type to generate for this branch</p>
                </div>
                <div className='grid grid-cols-3 gap-4'>
                    {REPORT_TYPES.map((report) => (
                        <div key={report.title} className='bg-white rounded-2xl p-5 shadow-sm flex flex-col gap-3'>
                            <div className='flex items-center justify-center w-9 h-9 rounded-lg bg-lime-50'>
                                <report.icon size={18} className='text-lime-700' />
                            </div>
                            <div>
                                <p className='font-semibold text-gray-800 text-sm'>{report.title}</p>
                                <p className='text-xs text-gray-500 mt-1'>{report.desc}</p>
                            </div>
                            <div className='flex items-center gap-2 mt-1'>
                                <button
                                    onClick={() => notConnected("be generated", report.title)}
                                    className='flex-1 bg-lime-400 hover:bg-lime-500 rounded-full py-2 text-sm font-semibold transition-colors'
                                >
                                    Generate
                                </button>
                                <button
                                    onClick={() => notConnected("be scheduled", report.title)}
                                    className='rounded-full px-4 py-2 text-sm font-semibold border border-gray-200 text-gray-700 hover:bg-gray-50 transition-colors'
                                >
                                    Schedule
                                </button>
                            </div>
                        </div>
                    ))}
                </div>
            </div>

            <div className='bg-white rounded-2xl p-5 shadow-sm'>
                <p className='font-semibold text-gray-800 mb-3'>Recently Generated</p>
                <table className='w-full text-sm'>
                    <thead>
                        <tr className='text-left text-gray-400 text-xs'>
                            <th className='font-medium pb-2'>Report</th>
                            <th className='font-medium pb-2'>Generated By</th>
                            <th className='font-medium pb-2'>Date</th>
                            <th className='font-medium pb-2'>Format</th>
                            <th className='font-medium pb-2'></th>
                        </tr>
                    </thead>
                    <tbody />
                </table>
                <p className='text-sm text-gray-400 text-center py-10'>No reports have been generated yet.</p>
            </div>

        </div>
    );
};

export default ReportsSection